version: '3'

#networks:
#  default:
#    external:
#      name: webapp

volumes:
  volguspsql:
  volgusmysql:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - php
      - postgres
      - mysql

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    image: voipgus/meuphp
    container_name: ${APP_NAME}_php
    restart: always
    volumes:
      - ./:/var/www/html
      #- ./storage:/var/www/html/storage:rw
    ports:
      - 9001:9001
  
  postgres:
    image: postgres:12.3-alpine
    container_name: ${APP_NAME}_postgres
    restart: always
    ports:
      - 5434:5432
    volumes:
      #- ./docker/postgres:/var/lib/postgresql/data
      - volguspsql:/var/lib/postgresql/data
      
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"

  mysql:
    #image: mysql:8.0
    image: mariadb:latest
    container_name: ${APP_NAME}_mysql
    restart: always
    tty: true
    ports:
      - 3310:3306
    volumes:
      #- ./docker/mysql:/var/lib/mysql/data
      - volgusmysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #SERVICE_TAGS: dev
      #SERVICE_NAME: mysql

  npm:
    image: node:13.7
    container_name: ${APP_NAME}_npm
    volumes:
      - ./:/var/www/html
    ports:
      - 3005:3000
      - 3007:3002
    working_dir: /var/www/html
    entrypoint: ['npm']
